const express=require("express");
const router=express.Router();
const db=require("../config/db");
const auth=require("../middleware/auth");
const roleAccess=require("../services/roleAccess");
let logger=null;try{logger=require("../utils/activityLogger");}catch(e){}
function clean(v,f=""){return String(v??f).trim();}
function parseId(v){const n=Number(v);return Number.isInteger(n)&&n>0?n:NaN;}
function canView(req){return roleAccess.isAdmin(req.user)||roleAccess.isManager(req.user)||roleAccess.isDigitalMarketing(req.user)||roleAccess.isTelecaller(req.user)||roleAccess.isSales(req.user)||roleAccess.hasPermission(req.user,"call_recording.view");}
function canManage(req){return roleAccess.isAdmin(req.user)||roleAccess.isManager(req.user)||roleAccess.isTelecaller(req.user)||roleAccess.isSales(req.user)||roleAccess.hasPermission(req.user,"call_recording.upload");}
async function ensureSchema(){await db.query(`CREATE TABLE IF NOT EXISTS call_logs(id SERIAL PRIMARY KEY,lead_id INTEGER REFERENCES leads(id),customer_name VARCHAR(200),customer_phone VARCHAR(30),call_direction VARCHAR(30) DEFAULT 'OUTBOUND',call_type VARCHAR(80) DEFAULT 'FOLLOW_UP',call_status VARCHAR(80) DEFAULT 'COMPLETED',call_started_at TIMESTAMP DEFAULT NOW(),call_duration_seconds INTEGER DEFAULT 0,recording_url TEXT,recording_file_name VARCHAR(250),summary TEXT,customer_response TEXT,next_followup_at TIMESTAMP,created_by INTEGER REFERENCES users(id),branch_id INTEGER,metadata JSONB DEFAULT '{}'::jsonb,created_at TIMESTAMP DEFAULT NOW(),updated_at TIMESTAMP DEFAULT NOW())`);await db.query(`CREATE INDEX IF NOT EXISTS idx_call_logs_lead ON call_logs(lead_id)`);await db.query(`CREATE INDEX IF NOT EXISTS idx_call_logs_created_by ON call_logs(created_by)`);}
async function audit(p){try{if(logger?.logActivity)await logger.logActivity(p);}catch(e){}}
router.get("/",auth,async(req,res)=>{try{await ensureSchema();if(!canView(req))return res.status(403).json({message:"No permission to view call logs"});const vals=[],clauses=["1=1"];if(req.query.lead_id){vals.push(parseId(req.query.lead_id));clauses.push(`cl.lead_id=$${vals.length}`);}if(!roleAccess.isAdmin(req.user)&&!roleAccess.isManager(req.user)&&!roleAccess.isDigitalMarketing(req.user)){vals.push(req.user.id);clauses.push(`cl.created_by=$${vals.length}`);}const r=await db.query(`SELECT cl.*,u.name AS created_by_name,l.name AS lead_name,l.status AS lead_status FROM call_logs cl LEFT JOIN users u ON u.id=cl.created_by LEFT JOIN leads l ON l.id=cl.lead_id WHERE ${clauses.join(" AND ")} ORDER BY cl.created_at DESC LIMIT 500`,vals);res.json(r.rows);}catch(e){console.error("CALL LOG LIST ERROR:",e);res.status(500).json({message:"Failed to load call logs"});}});
router.post("/",auth,async(req,res)=>{try{await ensureSchema();if(!canManage(req))return res.status(403).json({message:"No permission to create call log"});const leadId=parseId(req.body.lead_id);let lead=null;if(leadId){const lr=await db.query(`SELECT * FROM leads WHERE id=$1 LIMIT 1`,[leadId]);lead=lr.rows[0]||null;}const r=await db.query(`INSERT INTO call_logs(lead_id,customer_name,customer_phone,call_direction,call_type,call_status,call_started_at,call_duration_seconds,recording_url,recording_file_name,summary,customer_response,next_followup_at,created_by,branch_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) RETURNING *`,[leadId||null,clean(req.body.customer_name||lead?.name),clean(req.body.customer_phone||lead?.phone),clean(req.body.call_direction||"OUTBOUND").toUpperCase(),clean(req.body.call_type||"FOLLOW_UP").toUpperCase(),clean(req.body.call_status||"COMPLETED").toUpperCase(),req.body.call_started_at||new Date(),Number(req.body.call_duration_seconds||0),clean(req.body.recording_url),clean(req.body.recording_file_name),clean(req.body.summary),clean(req.body.customer_response),req.body.next_followup_at||null,req.user.id,req.user.branch_id||lead?.branch_id||lead?.assigned_branch_id||null,JSON.stringify(req.body.metadata||{})]);if(leadId&&(req.body.next_followup_at||req.body.customer_response||req.body.summary)){await db.query(`UPDATE leads SET status=CASE WHEN status IN ('BOOKED','CLOSED','LOST') THEN status ELSE 'FOLLOW-UP' END,next_followup_at=COALESCE($1,next_followup_at),updated_at=NOW() WHERE id=$2`,[req.body.next_followup_at||null,leadId]);try{await db.query(`INSERT INTO lead_followups(lead_id,user_id,followup_type,call_status,customer_response,remarks,next_followup_at) VALUES($1,$2,'CALL_LOG',$3,$4,$5,$6)`,[leadId,req.user.id,clean(req.body.call_status||"COMPLETED").toUpperCase(),clean(req.body.customer_response),clean(req.body.summary),req.body.next_followup_at||null]);}catch(e){}}await audit({req,user_id:req.user.id,lead_id:leadId||null,action:"CALL_LOG_CREATED",module_name:"CALL_RECORDING",entity_type:"CALL_LOG",entity_id:r.rows[0].id,new_value:clean(req.body.call_status||"COMPLETED").toUpperCase(),remarks:clean(req.body.summary||req.body.customer_response)});res.status(201).json({message:"Call log saved",call_log:r.rows[0]});}catch(e){console.error("CALL LOG CREATE ERROR:",e);res.status(500).json({message:"Failed to save call log"});}});
router.get("/summary",auth,async(req,res)=>{try{await ensureSchema();if(!canView(req))return res.status(403).json({message:"No permission to view call summary"});const vals=[],clauses=["1=1"];if(!roleAccess.isAdmin(req.user)&&!roleAccess.isManager(req.user)&&!roleAccess.isDigitalMarketing(req.user)){vals.push(req.user.id);clauses.push(`created_by=$${vals.length}`);}const r=await db.query(`SELECT COUNT(*)::int AS total_calls,COUNT(*) FILTER (WHERE call_status='COMPLETED')::int AS completed_calls,COUNT(*) FILTER (WHERE recording_url IS NOT NULL AND recording_url<>'')::int AS calls_with_recording,COALESCE(SUM(call_duration_seconds),0)::int AS total_duration_seconds FROM call_logs WHERE ${clauses.join(" AND ")}`,vals);res.json(r.rows[0]);}catch(e){console.error("CALL SUMMARY ERROR:",e);res.status(500).json({message:"Failed to load call summary"});}});
module.exports=router;
