const express=require("express");
const router=express.Router();
const db=require("../config/db");
const auth=require("../middleware/auth");
const comm=require("../services/communicationService");
function clean(v,f=""){return String(v??f).trim();}
function parseId(v){if(v===""||v===null||v===undefined)return null;const n=Number(v);return Number.isInteger(n)&&n>0?n:NaN;}
async function ensureSchema(){
 await db.query(`CREATE TABLE IF NOT EXISTS communication_templates(id SERIAL PRIMARY KEY,template_key VARCHAR(100) UNIQUE NOT NULL,channel VARCHAR(40) DEFAULT 'WHATSAPP',template_name VARCHAR(200),subject VARCHAR(250),body TEXT NOT NULL,trigger_event VARCHAR(100),is_auto_reply BOOLEAN DEFAULT false,is_active BOOLEAN DEFAULT true,created_by INTEGER REFERENCES users(id),created_at TIMESTAMP DEFAULT NOW(),updated_at TIMESTAMP DEFAULT NOW())`);
 await db.query(`CREATE TABLE IF NOT EXISTS communication_logs(id SERIAL PRIMARY KEY,lead_id INTEGER REFERENCES leads(id),customer_name VARCHAR(200),phone VARCHAR(30),email VARCHAR(200),channel VARCHAR(40),direction VARCHAR(40),template_key VARCHAR(100),subject VARCHAR(250),message_body TEXT,provider_name VARCHAR(100),provider_message_id VARCHAR(200),status VARCHAR(40) DEFAULT 'QUEUED',sent_by INTEGER REFERENCES users(id),metadata JSONB DEFAULT '{}'::jsonb,created_at TIMESTAMP DEFAULT NOW(),sent_at TIMESTAMP,delivered_at TIMESTAMP,read_at TIMESTAMP)`);
 await db.query(`CREATE INDEX IF NOT EXISTS idx_communication_logs_lead ON communication_logs(lead_id)`);
 await db.query(`CREATE INDEX IF NOT EXISTS idx_communication_logs_channel ON communication_logs(channel)`);
}
router.get("/templates",auth,async(req,res)=>{try{await ensureSchema();const r=await db.query(`SELECT * FROM communication_templates ORDER BY created_at DESC`);res.json(r.rows);}catch(e){console.error("COMM TPL LIST",e);res.status(500).json({message:"Failed to load templates"});}});
router.post("/templates",auth,async(req,res)=>{try{await ensureSchema();const key=clean(req.body.template_key).toUpperCase().replace(/[\s-]+/g,"_");if(!key||!clean(req.body.body))return res.status(400).json({message:"Template key and body required"});const r=await db.query(`INSERT INTO communication_templates(template_key,channel,template_name,subject,body,trigger_event,is_auto_reply,is_active,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(template_key) DO UPDATE SET channel=EXCLUDED.channel,template_name=EXCLUDED.template_name,subject=EXCLUDED.subject,body=EXCLUDED.body,trigger_event=EXCLUDED.trigger_event,is_auto_reply=EXCLUDED.is_auto_reply,is_active=EXCLUDED.is_active,updated_at=NOW() RETURNING *`,[key,comm.channel(req.body.channel),clean(req.body.template_name),clean(req.body.subject),clean(req.body.body),clean(req.body.trigger_event),req.body.is_auto_reply===true,req.body.is_active!==false,req.user.id]);res.status(201).json({message:"Template saved",template:r.rows[0]});}catch(e){console.error("COMM TPL SAVE",e);res.status(500).json({message:"Failed to save template"});}});
router.get("/logs",auth,async(req,res)=>{try{await ensureSchema();const vals=[],clauses=["1=1"];if(req.query.lead_id){vals.push(parseId(req.query.lead_id));clauses.push(`cl.lead_id=$${vals.length}`);}const r=await db.query(`SELECT cl.*,u.name AS sent_by_name,l.name AS lead_name,l.status AS lead_status FROM communication_logs cl LEFT JOIN users u ON u.id=cl.sent_by LEFT JOIN leads l ON l.id=cl.lead_id WHERE ${clauses.join(" AND ")} ORDER BY cl.created_at DESC LIMIT 500`,vals);res.json(r.rows);}catch(e){console.error("COMM LOG LIST",e);res.status(500).json({message:"Failed to load logs"});}});
router.post("/send",auth,async(req,res)=>{try{await ensureSchema();const leadId=parseId(req.body.lead_id);let lead=null;if(leadId){const lr=await db.query(`SELECT * FROM leads WHERE id=$1 LIMIT 1`,[leadId]);lead=lr.rows[0]||null;}let subject=clean(req.body.subject),body=clean(req.body.message_body),key=clean(req.body.template_key).toUpperCase();if(key&&!body){const tr=await db.query(`SELECT * FROM communication_templates WHERE template_key=$1 AND is_active=true LIMIT 1`,[key]);const t=tr.rows[0];if(t){subject=comm.renderTemplate(t.subject,lead||{});body=comm.renderTemplate(t.body,lead||{});}}if(!body)return res.status(400).json({message:"Message body required"});const ch=comm.channel(req.body.channel);const phone=clean(req.body.phone||lead?.phone);const email=clean(req.body.email||lead?.email);const log=await comm.logCommunication(db,{lead_id:leadId,customer_name:clean(req.body.customer_name||lead?.name),phone,email,channel:ch,direction:"OUTBOUND",template_key:key,subject,message_body:body,provider_name:"MANUAL_LINK",status:"QUEUED",sent_by:req.user.id,metadata:{whatsapp_url:ch==="WHATSAPP"?comm.waUrl(phone,body):"",mailto_url:ch==="EMAIL"?comm.mailto(email,subject,body):""}});res.status(201).json({message:"Communication prepared",log,whatsapp_url:log.metadata?.whatsapp_url||"",mailto_url:log.metadata?.mailto_url||""});}catch(e){console.error("COMM SEND",e);res.status(500).json({message:"Failed to prepare communication"});}});
module.exports=router;
