const express=require("express");
const router=express.Router();
const db=require("../config/db");
const auth=require("../middleware/auth");
function clean(v,f=""){return String(v??f).trim();}
function parseId(v){if(v===""||v===null||v===undefined)return null;const n=Number(v);return Number.isInteger(n)&&n>0?n:NaN;}
async function safeQuery(sql,params=[]){try{const r=await db.query(sql,params);return r.rows||[];}catch(e){return[];}}
async function ensureSchema(){await db.query(`CREATE TABLE IF NOT EXISTS customer_timeline_notes(id SERIAL PRIMARY KEY,lead_id INTEGER REFERENCES leads(id),note_type VARCHAR(80) DEFAULT 'MANUAL',title VARCHAR(250),note TEXT,created_by INTEGER REFERENCES users(id),created_at TIMESTAMP DEFAULT NOW())`);await db.query(`CREATE INDEX IF NOT EXISTS idx_customer_timeline_notes_lead ON customer_timeline_notes(lead_id)`);}
function item(o){return{type:o.type,title:o.title,description:o.description,event_time:o.event_time,actor:o.actor,status:o.status,priority:o.priority,source:o.source,entity_id:o.entity_id,metadata:o.metadata||{}};}
router.get("/lead/:id",auth,async(req,res)=>{try{await ensureSchema();const leadId=parseId(req.params.id);if(!leadId)return res.status(400).json({message:"Invalid lead id"});const lr=await db.query(`SELECT l.*,u.name AS assigned_name,b.branch_name FROM leads l LEFT JOIN users u ON u.id=l.assigned_to LEFT JOIN branches b ON b.id=COALESCE(l.branch_id,l.assigned_branch_id) WHERE l.id=$1 LIMIT 1`,[leadId]);if(!lr.rows.length)return res.status(404).json({message:"Lead not found"});const lead=lr.rows[0];const items=[];
items.push(item({type:"LEAD_CREATED",title:"Lead Created",description:`${lead.name||"Customer"} enquiry created from ${lead.source||"unknown source"}`,event_time:lead.created_at,actor:lead.assigned_name||"System",status:lead.status,priority:lead.priority,source:lead.source,entity_id:lead.id,metadata:{phone:lead.phone,car_interest:lead.car_interest,branch_name:lead.branch_name}}));
(await safeQuery(`SELECT f.*,u.name AS user_name FROM lead_followups f LEFT JOIN users u ON u.id=f.user_id WHERE f.lead_id=$1 ORDER BY f.created_at ASC`,[leadId])).forEach(f=>items.push(item({type:"FOLLOW_UP",title:f.followup_type||"Follow-up",description:f.remarks||f.customer_response||f.call_status||"Follow-up activity",event_time:f.created_at,actor:f.user_name||"System",status:f.call_status||f.followup_status,source:"FOLLOWUP",entity_id:f.id,metadata:f})));
(await safeQuery(`SELECT cl.*,u.name AS sent_by_name FROM communication_logs cl LEFT JOIN users u ON u.id=cl.sent_by WHERE cl.lead_id=$1 ORDER BY cl.created_at ASC`,[leadId])).forEach(c=>items.push(item({type:"COMMUNICATION",title:`${c.channel||"Communication"} ${c.direction||""}`.trim(),description:c.message_body||c.subject||"Communication activity",event_time:c.created_at,actor:c.sent_by_name||c.provider_name||"System",status:c.status,source:c.channel,entity_id:c.id,metadata:c})));
(await safeQuery(`SELECT n.*,u.name AS assigned_user_name FROM notifications n LEFT JOIN users u ON u.id=n.assigned_to WHERE n.lead_id=$1 ORDER BY n.created_at ASC`,[leadId])).forEach(n=>items.push(item({type:"NOTIFICATION",title:n.title,description:n.message,event_time:n.created_at,actor:n.assigned_user_name||"System",status:n.is_read?"READ":"UNREAD",priority:n.priority,source:n.notification_type,entity_id:n.id,metadata:n})));
(await safeQuery(`SELECT d.*,rb.name AS requested_by_name,ab.name AS approved_by_name FROM data_change_requests d LEFT JOIN users rb ON rb.id=d.requested_by LEFT JOIN users ab ON ab.id=d.approved_by WHERE d.entity_type='LEAD' AND d.entity_id=$1 ORDER BY d.created_at ASC`,[leadId])).forEach(a=>items.push(item({type:"APPROVAL",title:`${a.action_type} Approval Request`,description:a.reason||a.approver_remarks||"Data change approval activity",event_time:a.created_at,actor:a.requested_by_name||"Requester",status:a.request_status,priority:a.request_status==="PENDING"?"HIGH":"NORMAL",source:"DATA_GOVERNANCE",entity_id:a.id,metadata:a})));
(await safeQuery(`SELECT q.*,u.name AS created_by_name FROM quick_enquiries q LEFT JOIN users u ON u.id=q.created_by WHERE q.lead_id=$1 OR q.phone=$2 ORDER BY q.created_at ASC`,[leadId,lead.phone])).forEach(q=>items.push(item({type:"QUICK_ENQUIRY",title:"Quick Enquiry",description:`${q.source_type||"Quick source"} - ${q.notes||""}`,event_time:q.created_at,actor:q.created_by_name||"Sales",status:q.quick_status,source:q.source_type,entity_id:q.id,metadata:q})));
(await safeQuery(`SELECT s.*,qs.session_name FROM showroom_qr_submissions s LEFT JOIN showroom_qr_sessions qs ON qs.id=s.session_id WHERE s.lead_id=$1 OR s.phone=$2 ORDER BY s.created_at ASC`,[leadId,lead.phone])).forEach(q=>items.push(item({type:"SHOWROOM_QR",title:"Showroom QR Submission",description:q.session_name||q.submission_method||"Customer QR form submitted",event_time:q.created_at,actor:"Customer / Reception",status:q.submission_status,source:"SHOWROOM_QR",entity_id:q.id,metadata:q})));
(await safeQuery(`SELECT b.* FROM bookings b WHERE b.lead_id=$1 ORDER BY b.created_at ASC`,[leadId])).forEach(b=>items.push(item({type:"BOOKING",title:"Booking Activity",description:`${b.booking_status||b.status||"Booking"}`,event_time:b.created_at,actor:"Sales",status:b.booking_status||b.status,source:"BOOKING",entity_id:b.id,metadata:b})));
(await safeQuery(`SELECT d.* FROM deliveries d WHERE d.lead_id=$1 ORDER BY d.created_at ASC`,[leadId])).forEach(d=>items.push(item({type:"DELIVERY",title:"Delivery Activity",description:d.delivery_status||d.status||"Delivery workflow",event_time:d.created_at,actor:"Delivery Team",status:d.delivery_status||d.status,source:"DELIVERY",entity_id:d.id,metadata:d})));
(await safeQuery(`SELECT n.*,u.name AS created_by_name FROM customer_timeline_notes n LEFT JOIN users u ON u.id=n.created_by WHERE n.lead_id=$1 ORDER BY n.created_at ASC`,[leadId])).forEach(n=>items.push(item({type:n.note_type||"NOTE",title:n.title||"Timeline Note",description:n.note,event_time:n.created_at,actor:n.created_by_name||"User",status:"NOTE",source:"MANUAL",entity_id:n.id,metadata:n})));
items.sort((a,b)=>new Date(b.event_time||0)-new Date(a.event_time||0));res.json({lead,summary:{total_events:items.length,communications:items.filter(i=>i.type==="COMMUNICATION").length,followups:items.filter(i=>i.type==="FOLLOW_UP").length,approvals:items.filter(i=>i.type==="APPROVAL").length,bookings:items.filter(i=>i.type==="BOOKING").length,notifications:items.filter(i=>i.type==="NOTIFICATION").length},timeline:items});}catch(e){console.error("CUSTOMER TIMELINE ERROR:",e);res.status(500).json({message:"Failed to load customer timeline"});}});
router.post("/lead/:id/note",auth,async(req,res)=>{try{await ensureSchema();const leadId=parseId(req.params.id);if(!leadId)return res.status(400).json({message:"Invalid lead id"});const r=await db.query(`INSERT INTO customer_timeline_notes(lead_id,note_type,title,note,created_by) VALUES($1,$2,$3,$4,$5) RETURNING *`,[leadId,clean(req.body.note_type||"MANUAL"),clean(req.body.title||"Timeline Note"),clean(req.body.note),req.user.id]);res.status(201).json({message:"Timeline note added",note:r.rows[0]});}catch(e){console.error("CUSTOMER TIMELINE NOTE ERROR:",e);res.status(500).json({message:"Failed to add timeline note"});}});
module.exports=router;