const express=require("express");
const router=express.Router();
const db=require("../config/db");
const auth=require("../middleware/auth");
const dataGov=require("../services/dataActionGovernance");
let logger=null;try{logger=require("../utils/activityLogger");}catch(e){}
function clean(v,f=""){return String(v??f).trim();}
function parseId(v){const id=Number(v);return Number.isInteger(id)&&id>0?id:NaN;}
async function ensureSchema(){await db.query(`CREATE TABLE IF NOT EXISTS data_change_requests(id SERIAL PRIMARY KEY,entity_type VARCHAR(80) NOT NULL,entity_id INTEGER,action_type VARCHAR(40) NOT NULL,requested_by INTEGER REFERENCES users(id),approved_by INTEGER REFERENCES users(id),request_status VARCHAR(40) DEFAULT 'PENDING',current_payload JSONB DEFAULT '{}'::jsonb,requested_payload JSONB DEFAULT '{}'::jsonb,reason TEXT,approver_remarks TEXT,created_at TIMESTAMP DEFAULT NOW(),reviewed_at TIMESTAMP,updated_at TIMESTAMP DEFAULT NOW())`);await db.query(`CREATE INDEX IF NOT EXISTS idx_data_change_requests_status ON data_change_requests(request_status)`);await db.query(`CREATE INDEX IF NOT EXISTS idx_data_change_requests_entity ON data_change_requests(entity_type,entity_id)`);await db.query(`CREATE INDEX IF NOT EXISTS idx_data_change_requests_requested_by ON data_change_requests(requested_by)`);}
async function audit(p){try{if(logger?.logActivity)await logger.logActivity(p);}catch(e){}}
router.get("/rights",auth,async(req,res)=>{res.json(dataGov.actionRights(req.user));});
router.get("/",auth,async(req,res)=>{try{await ensureSchema();const vals=[],clauses=["1=1"];if(!dataGov.canApproveDataChange(req.user)){vals.push(req.user.id);clauses.push(`r.requested_by=$${vals.length}`);}if(req.query.status){vals.push(clean(req.query.status).toUpperCase());clauses.push(`r.request_status=$${vals.length}`);}const r=await db.query(`SELECT r.*,rb.name AS requested_by_name,ab.name AS approved_by_name FROM data_change_requests r LEFT JOIN users rb ON rb.id=r.requested_by LEFT JOIN users ab ON ab.id=r.approved_by WHERE ${clauses.join(" AND ")} ORDER BY r.created_at DESC LIMIT 300`,vals);res.json(r.rows);}catch(e){console.error("DATA CHANGE LIST ERROR:",e);res.status(500).json({message:"Failed to load data change requests"});}});
router.post("/",auth,async(req,res)=>{try{await ensureSchema();const entityType=clean(req.body.entity_type).toUpperCase();const actionType=clean(req.body.action_type).toUpperCase();if(!entityType||!["EDIT","DELETE"].includes(actionType))return res.status(400).json({message:"Valid entity_type and action_type are required"});const r=await db.query(`INSERT INTO data_change_requests(entity_type,entity_id,action_type,requested_by,current_payload,requested_payload,reason) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[entityType,req.body.entity_id||null,actionType,req.user.id,JSON.stringify(req.body.current_payload||{}),JSON.stringify(req.body.requested_payload||{}),clean(req.body.reason)]);await audit({req,user_id:req.user.id,action:"DATA_CHANGE_REQUEST_CREATED",module_name:"GOVERNANCE",entity_type:"DATA_CHANGE_REQUEST",entity_id:r.rows[0].id,new_value:"PENDING",remarks:`${actionType} request submitted for ${entityType}`});res.status(201).json({message:"Data change request submitted for approval",request:r.rows[0]});}catch(e){console.error("DATA CHANGE CREATE ERROR:",e);res.status(500).json({message:"Failed to submit data change request"});}});
router.post("/:id/review",auth,async(req,res)=>{try{await ensureSchema();if(!dataGov.canApproveDataChange(req.user))return res.status(403).json({message:"You do not have approval authority"});const id=parseId(req.params.id);if(Number.isNaN(id))return res.status(400).json({message:"Invalid request id"});const status=clean(req.body.request_status).toUpperCase();if(!["APPROVED","REJECTED"].includes(status))return res.status(400).json({message:"Status must be APPROVED or REJECTED"});const r=await db.query(`UPDATE data_change_requests SET request_status=$1,approved_by=$2,approver_remarks=$3,reviewed_at=NOW(),updated_at=NOW() WHERE id=$4 AND request_status='PENDING' RETURNING *`,[status,req.user.id,clean(req.body.approver_remarks),id]);if(!r.rows.length)return res.status(404).json({message:"Pending request not found"});await audit({req,user_id:req.user.id,action:`DATA_CHANGE_REQUEST_${status}`,module_name:"GOVERNANCE",entity_type:"DATA_CHANGE_REQUEST",entity_id:id,new_value:status,remarks:clean(req.body.approver_remarks)});res.json({message:`Request ${status.toLowerCase()}`,request:r.rows[0]});}catch(e){console.error("DATA CHANGE REVIEW ERROR:",e);res.status(500).json({message:"Failed to review data change request"});}});
module.exports=router;