CREATE TABLE IF NOT EXISTS users (
 id BIGSERIAL PRIMARY KEY,
 name TEXT NOT NULL,
 email TEXT NOT NULL UNIQUE,
 password TEXT NOT NULL,
 role TEXT NOT NULL DEFAULT 'sales' CHECK (role IN ('admin','sales')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS leads (
 id BIGSERIAL PRIMARY KEY,
 name TEXT NOT NULL,
 phone TEXT NOT NULL,
 email TEXT DEFAULT '',
 area TEXT DEFAULT '',
 district TEXT DEFAULT '',
 profession TEXT DEFAULT '',
 car_interest TEXT DEFAULT 'Not Selected',
 action_type TEXT DEFAULT 'ENQUIRY',
 source TEXT DEFAULT 'Website',
 tracking JSONB DEFAULT '{}'::jsonb,
 score INTEGER DEFAULT 0,
 priority TEXT DEFAULT 'COLD' CHECK (priority IN ('HOT','WARM','COLD')),
 status TEXT DEFAULT 'NEW' CHECK (status IN ('NEW','CONTACTED','FOLLOW-UP','TEST-DRIVE','BOOKED','CLOSED','LOST')),
 assigned_to BIGINT REFERENCES users(id) ON DELETE SET NULL,
 notes TEXT DEFAULT '',
 followup_1 TIMESTAMPTZ,
 followup_2 TIMESTAMPTZ,
 followup_3 TIMESTAMPTZ,
 f1_sent BOOLEAN DEFAULT FALSE,
 f2_sent BOOLEAN DEFAULT FALSE,
 f3_sent BOOLEAN DEFAULT FALSE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_leads_assigned_to ON leads(assigned_to);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(status);
CREATE INDEX IF NOT EXISTS idx_leads_priority ON leads(priority);
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON leads(created_at DESC);

-- Safe upgrade commands for older project databases
ALTER TABLE leads ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'Website';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS assigned_to BIGINT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT '';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS followup_1 TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS followup_2 TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS followup_3 TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS f1_sent BOOLEAN DEFAULT FALSE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS f2_sent BOOLEAN DEFAULT FALSE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS f3_sent BOOLEAN DEFAULT FALSE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE leads ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
