-- Strong 500 compatibility fix for branches and leads

ALTER TABLE branches
ADD COLUMN IF NOT EXISTS branch_name VARCHAR(200),
ADD COLUMN IF NOT EXISTS branch_code VARCHAR(80),
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS area VARCHAR(150),
ADD COLUMN IF NOT EXISTS city VARCHAR(150),
ADD COLUMN IF NOT EXISTS district VARCHAR(150),
ADD COLUMN IF NOT EXISTS state VARCHAR(150),
ADD COLUMN IF NOT EXISTS pincode VARCHAR(30),
ADD COLUMN IF NOT EXISTS latitude NUMERIC(12,8),
ADD COLUMN IF NOT EXISTS longitude NUMERIC(12,8),
ADD COLUMN IF NOT EXISTS manager_id INTEGER,
ADD COLUMN IF NOT EXISTS phone VARCHAR(30),
ADD COLUMN IF NOT EXISTS email VARCHAR(200),
ADD COLUMN IF NOT EXISTS status VARCHAR(40) DEFAULT 'ACTIVE',
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();

ALTER TABLE leads
ADD COLUMN IF NOT EXISTS vehicle_category VARCHAR(20),
ADD COLUMN IF NOT EXISTS branch_id INTEGER,
ADD COLUMN IF NOT EXISTS assigned_branch_id INTEGER,
ADD COLUMN IF NOT EXISTS assigned_to INTEGER,
ADD COLUMN IF NOT EXISTS next_followup_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS next_followup_date TIMESTAMP,
ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS deleted_by INTEGER,
ADD COLUMN IF NOT EXISTS delete_reason TEXT,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();

UPDATE leads SET vehicle_category='AD' WHERE vehicle_category IS NULL OR TRIM(vehicle_category)='';
UPDATE leads SET is_deleted=false WHERE is_deleted IS NULL;

CREATE INDEX IF NOT EXISTS idx_leads_is_deleted ON leads(is_deleted);
CREATE INDEX IF NOT EXISTS idx_branches_manager_id ON branches(manager_id);
